"""Reporter: a Strands Agents SDK agent that files the 1930 helpline packet.

Invoked by Step Functions after an EventBridge `drill.tripped` / `drill.ended` event.
Input: {"drillId": "...", "ddbTable": "...", "bucket": "..."}
Reads the drill record from DynamoDB, asks a Strands agent (on Bedrock) for the narrative
sections, assembles the markdown packet deterministically, writes it to S3 and the presigned
URL back into the record.
"""
import json
import os
import time
from datetime import datetime, timezone

import boto3

REGION = os.environ.get("BEDROCK_REGION", os.environ.get("AWS_REGION", "ap-south-1"))
MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "anthropic.claude-haiku-4-5-20251001-v1:0")

ddb = boto3.resource("dynamodb")
s3 = boto3.client("s3")


def hms(ms: float) -> str:
    s = max(0, int(round(ms / 1000)))
    return f"{s // 60:02d}:{s % 60:02d}"


def narrative(rec: dict) -> str:
    """Ask a Strands agent for the two prose sections. Falls back to a plain summary."""
    d = rec["summary"]
    lines = [f"[{u['speaker']}] {u['text']}" for u in rec.get("utterances", [])][:40]
    prompt = (
        "You are the Reporter in a scam-awareness drill. Write two short sections for a cyber-fraud "
        "complaint draft to India's 1930 helpline, in plain English, for a FICTIONAL incident that happened "
        "in a training simulation. Section 1 'Summary of the incident' (3-4 sentences, past tense, third person). "
        "Section 2 'Coercion tactics observed' (bullet list, one line per tactic, cite the line that shows it). "
        "Do not invent facts beyond the transcript. Mark clearly that this was a drill.\n\n"
        f"Victim (fictional): {d['world']['personaName']}, {d['world']['personaAge']}, {d['world']['city']}\n"
        f"Caller claimed: {d['caller']['name']}, {d['caller']['org']}\nCase family: {d['familyLabel']}\n"
        f"Outcome: {rec.get('ending', 'unknown')}\n\nTranscript:\n" + "\n".join(lines)
    )
    try:
        from strands import Agent
        from strands.models import BedrockModel

        agent = Agent(
            model=BedrockModel(model_id=MODEL_ID, region_name=REGION, temperature=0.2, max_tokens=700),
            system_prompt="You write precise, non-sensational complaint drafts. Never add information that is not in the transcript.",
            callback_handler=None,
        )
        result = agent(prompt)
        text = str(result).strip()
        if text:
            return text
    except Exception as e:  # noqa: BLE001
        print("strands agent failed, using fallback:", repr(e))
    tactics = sorted({t for m in rec.get("moves", []) for t in m.get("tactics", [])})
    return (
        "## Summary of the incident\n\n"
        f"During a training drill, a caller claiming to be {d['caller']['name']} of {d['caller']['org']} contacted "
        f"{d['world']['personaName']} and applied pressure consistent with a {d['familyLabel'].lower()} scam. "
        f"The drill ended with outcome {rec.get('ending', 'unknown')}.\n\n"
        "## Coercion tactics observed\n\n" + "\n".join(f"- {t.replace('_', ' ').title()}" for t in tactics)
    )


def packet(rec: dict, prose: str) -> str:
    d = rec["summary"]
    t0 = d.get("startedAt") or d["createdAt"]
    out = [
        "# Cyber Fraud Report — draft for helpline 1930 / cybercrime.gov.in",
        "",
        "**Generated by:** Circuit Breaker drill (simulation — no real fraud occurred)",
        f"**Victim (fictional):** {d['world']['personaName']}, {d['world']['personaAge']}, {d['world']['city']}",
        f"**Modus operandi:** {d['familyLabel']} via {d['channel']}",
        f"**Caller identity claimed:** {d['caller']['name']}, {d['caller']['org']}, {d['caller']['number']}",
        f"**Session:** {datetime.fromtimestamp(t0 / 1000, tz=timezone.utc).isoformat()} · duration {hms((d.get('endedAt') or time.time() * 1000) - t0)} · outcome {rec.get('ending', 'in progress')}",
        "",
        prose,
        "",
        "## Coercion timeline",
        "| Time | Speaker | Line | Index |",
        "| --- | --- | --- | --- |",
    ]
    moves = rec.get("moves", [])
    for u in rec.get("utterances", []):
        idx = next((m["index"] for m in moves if m.get("quote") and m["quote"][:30] in u["text"]), "")
        out.append(f"| {hms(u['ts'] - t0)} | {u['speaker']} | {u['text'].replace('|', '/')} | {idx} |")
    out += ["", "## Session signals"] + [f"- {hms(s['ts'] - t0)} · {s['kind']} (+{s['delta']})" for s in rec.get("signals", [])]
    out += ["", "## Breaker"] + [f"- {hms(l['ts'] - t0)} · {l['from']} → {l['to']} at index {l['index']}" for l in rec.get("ladderSteps", [])]
    if rec.get("trip"):
        out.append(f"- **Tripped at {hms(rec['trip']['ts'] - t0)}**, index {rec['trip']['index']}. Family contact {d['world']['guardian']['name']} was put on the line.")
    out += ["", "## Numbers and identifiers to report", f"- Caller number: {d['caller']['number']}", f"- Claimed organisation: {d['caller']['org']}"]
    if rec.get("leaked"):
        out += ["", "## Information disclosed"] + [f"- {l}" for l in rec["leaked"]]
    out += ["", "---", "This document was produced by a drill. Nothing in it describes a real incident.", "Filed by the Reporter (Strands Agents SDK on AWS Lambda)."]
    return "\n".join(out)


def main(event, _context):
    drill_id = event["drillId"]
    table = ddb.Table(event.get("ddbTable") or os.environ["DDB_TABLE"])
    bucket = event.get("bucket") or os.environ["S3_PACKET_BUCKET"]
    item = table.get_item(Key={"pk": drill_id, "sk": "DRILL"}).get("Item")
    if not item:
        return {"ok": False, "reason": "drill not found", "drillId": drill_id}
    rec = json.loads(item["data"])
    md = packet(rec, narrative(rec))
    key = f"packets/{drill_id}/packet.md"
    s3.put_object(Bucket=bucket, Key=key, Body=md.encode("utf-8"), ContentType="text/markdown")
    url = s3.generate_presigned_url("get_object", Params={"Bucket": bucket, "Key": key}, ExpiresIn=3600)
    rec["packet"] = {"md": md, "url": url, "status": "ready"}
    table.put_item(Item={**item, "data": json.dumps(rec), "updatedAt": int(time.time() * 1000)})
    return {"ok": True, "drillId": drill_id, "key": key}
