import type { DrillRecord } from "./store";
import { cfg } from "./config";
import { s3, eventbridge } from "./aws";
import { ontology } from "./corpus";

function hms(ms: number) { const s = Math.max(0, Math.round(ms / 1000)); return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`; }

export function buildPacketMarkdown(rec: DrillRecord): string {
  const d = rec.summary; const t0 = d.startedAt ?? d.createdAt;
  const lines = [
    `# Cyber Fraud Report — draft for helpline 1930 / cybercrime.gov.in`,
    ``,
    `**Generated by:** Circuit Breaker drill (simulation — no real fraud occurred)`,
    `**Victim (fictional):** ${d.world.personaName}, ${d.world.personaAge}, ${d.world.city}`,
    `**Modus operandi:** ${d.familyLabel} via ${d.channel}`,
    `**Caller identity claimed:** ${d.caller.name}, ${d.caller.org}, ${d.caller.number}`,
    `**Session:** ${new Date(t0).toLocaleString("en-IN")} · duration ${hms((d.endedAt ?? Date.now()) - t0)} · outcome ${rec.ending ?? "in progress"}`,
    ``,
    `## Coercion timeline`,
    `| Time | Speaker | Line | Tactics | Index |`,
    `| --- | --- | --- | --- | --- |`,
  ];
  for (const u of rec.utterances) {
    const mv = rec.moves.find((m) => m.quote && u.text.includes(m.quote.slice(0, 30)));
    lines.push(`| ${hms(u.ts - t0)} | ${u.speaker}${u.name ? ` (${u.name})` : ""} | ${u.text.replace(/\|/g, "/")} | ${mv ? mv.tactics.join(", ") : ""} | ${mv ? mv.index : ""} |`);
  }
  lines.push(``, `## Session signals`);
  for (const s of rec.signals) lines.push(`- ${hms(s.ts - t0)} · ${ontology.signals[s.kind]?.label ?? s.kind} (+${s.delta})`);
  lines.push(``, `## Breaker`);
  for (const l of rec.ladderSteps) lines.push(`- ${hms(l.ts - t0)} · ${l.from} → ${l.to} at index ${l.index}`);
  if (rec.trip) lines.push(`- **Tripped at ${hms(rec.trip.ts - t0)}**, index ${rec.trip.index}. Family contact ${d.world.guardian.name} was put on the line.`);
  lines.push(``, `## Numbers and identifiers to report`, `- Caller number: ${d.caller.number}`, `- Claimed organisation: ${d.caller.org}`);
  if (rec.leaked.length) lines.push(``, `## Information disclosed`, ...rec.leaked.map((l) => `- ${l}`));
  lines.push(``, `---`, `This document was produced by a drill. Nothing in it describes a real incident.`);
  return lines.join("\n");
}

export async function filePacket(rec: DrillRecord, onProgress: (p: number) => void): Promise<{ url: string; status: "ready" | "pending" }> {
  onProgress(20);
  const md = buildPacketMarkdown(rec);
  rec.packet = { md, status: "pending" };
  // Serverless pipeline: EventBridge → Step Functions → Strands Reporter Lambda → S3 → DynamoDB
  if (cfg.eventBus) {
    try {
      const eb = await eventbridge();
      const { PutEventsCommand } = await import("@aws-sdk/client-eventbridge");
      await eb.send(new PutEventsCommand({ Entries: [{ EventBusName: cfg.eventBus, Source: "circuit-breaker", DetailType: rec.trip ? "drill.tripped" : "drill.ended", Detail: JSON.stringify({ drillId: rec.summary.id, ddbTable: cfg.ddbTable, bucket: cfg.s3Bucket }) }] }));
      onProgress(60);
      return { url: `/api/drills/${rec.summary.id}/packet`, status: "pending" };
    } catch (e) { console.warn("[reporter] eventbridge failed, in-process:", (e as Error).message); }
  }
  onProgress(60);
  if (cfg.s3Bucket) {
    try {
      const client = await s3();
      const { PutObjectCommand, GetObjectCommand } = await import("@aws-sdk/client-s3");
      const { getSignedUrl } = await import("@aws-sdk/s3-request-presigner");
      const key = `packets/${rec.summary.id}/packet.md`;
      await client.send(new PutObjectCommand({ Bucket: cfg.s3Bucket, Key: key, Body: md, ContentType: "text/markdown" }));
      const url = await getSignedUrl(client, new GetObjectCommand({ Bucket: cfg.s3Bucket, Key: key }), { expiresIn: 3600 });
      rec.packet = { md, url, status: "ready" };
      onProgress(100);
      return { url, status: "ready" };
    } catch (e) { console.warn("[reporter] s3 failed, served locally:", (e as Error).message); }
  }
  rec.packet = { md, url: `/api/drills/${rec.summary.id}/packet`, status: "ready" };
  onProgress(100);
  return { url: rec.packet.url!, status: "ready" };
}
