/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowRouteImport } from './routes/how'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiDrillsRouteImport } from './routes/api/drills'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DrillDrillIdRouteImport } from './routes/drill/$drillId'
import { Route as DrillNewRouteImport } from './routes/drill/new'
import { Route as ApiDrillsDrillIdRouteImport } from './routes/api/drills.$drillId'
import { Route as DrillDrillIdDebriefRouteImport } from './routes/drill/$drillId_.debrief'
import { Route as ApiDrillsDrillIdDebriefRouteImport } from './routes/api/drills.$drillId.debrief'
import { Route as ApiDrillsDrillIdEndRouteImport } from './routes/api/drills.$drillId.end'
import { Route as ApiDrillsDrillIdPacketRouteImport } from './routes/api/drills.$drillId.packet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillsRoute = ApiDrillsRouteImport.update({
  id: '/api/drills',
  path: '/api/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillDrillIdRoute = DrillDrillIdRouteImport.update({
  id: '/drill/$drillId',
  path: '/drill/$drillId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillNewRoute = DrillNewRouteImport.update({
  id: '/drill/new',
  path: '/drill/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillsDrillIdRoute = ApiDrillsDrillIdRouteImport.update({
  id: '/$drillId',
  path: '/$drillId',
  getParentRoute: () => ApiDrillsRoute,
} as any)
const DrillDrillIdDebriefRoute = DrillDrillIdDebriefRouteImport.update({
  id: '/drill/$drillId_/debrief',
  path: '/drill/$drillId/debrief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillsDrillIdDebriefRoute = ApiDrillsDrillIdDebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => ApiDrillsDrillIdRoute,
} as any)
const ApiDrillsDrillIdEndRoute = ApiDrillsDrillIdEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => ApiDrillsDrillIdRoute,
} as any)
const ApiDrillsDrillIdPacketRoute = ApiDrillsDrillIdPacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => ApiDrillsDrillIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/drills': typeof ApiDrillsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/drill/$drillId': typeof DrillDrillIdRoute
  '/drill/new': typeof DrillNewRoute
  '/api/drills/$drillId': typeof ApiDrillsDrillIdRouteWithChildren
  '/drill/$drillId/debrief': typeof DrillDrillIdDebriefRoute
  '/api/drills/$drillId/debrief': typeof ApiDrillsDrillIdDebriefRoute
  '/api/drills/$drillId/end': typeof ApiDrillsDrillIdEndRoute
  '/api/drills/$drillId/packet': typeof ApiDrillsDrillIdPacketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/drills': typeof ApiDrillsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/drill/$drillId': typeof DrillDrillIdRoute
  '/drill/new': typeof DrillNewRoute
  '/api/drills/$drillId': typeof ApiDrillsDrillIdRouteWithChildren
  '/drill/$drillId/debrief': typeof DrillDrillIdDebriefRoute
  '/api/drills/$drillId/debrief': typeof ApiDrillsDrillIdDebriefRoute
  '/api/drills/$drillId/end': typeof ApiDrillsDrillIdEndRoute
  '/api/drills/$drillId/packet': typeof ApiDrillsDrillIdPacketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/drills': typeof ApiDrillsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/drill/$drillId': typeof DrillDrillIdRoute
  '/drill/new': typeof DrillNewRoute
  '/api/drills/$drillId': typeof ApiDrillsDrillIdRouteWithChildren
  '/drill/$drillId_/debrief': typeof DrillDrillIdDebriefRoute
  '/api/drills/$drillId/debrief': typeof ApiDrillsDrillIdDebriefRoute
  '/api/drills/$drillId/end': typeof ApiDrillsDrillIdEndRoute
  '/api/drills/$drillId/packet': typeof ApiDrillsDrillIdPacketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how'
    | '/api/catalog'
    | '/api/drills'
    | '/api/health'
    | '/drill/$drillId'
    | '/drill/new'
    | '/api/drills/$drillId'
    | '/drill/$drillId/debrief'
    | '/api/drills/$drillId/debrief'
    | '/api/drills/$drillId/end'
    | '/api/drills/$drillId/packet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/api/catalog'
    | '/api/drills'
    | '/api/health'
    | '/drill/$drillId'
    | '/drill/new'
    | '/api/drills/$drillId'
    | '/drill/$drillId/debrief'
    | '/api/drills/$drillId/debrief'
    | '/api/drills/$drillId/end'
    | '/api/drills/$drillId/packet'
  id:
    | '__root__'
    | '/'
    | '/how'
    | '/api/catalog'
    | '/api/drills'
    | '/api/health'
    | '/drill/$drillId'
    | '/drill/new'
    | '/api/drills/$drillId'
    | '/drill/$drillId_/debrief'
    | '/api/drills/$drillId/debrief'
    | '/api/drills/$drillId/end'
    | '/api/drills/$drillId/packet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiDrillsRoute: typeof ApiDrillsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  DrillDrillIdRoute: typeof DrillDrillIdRoute
  DrillNewRoute: typeof DrillNewRoute
  DrillDrillIdDebriefRoute: typeof DrillDrillIdDebriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drills': {
      id: '/api/drills'
      path: '/api/drills'
      fullPath: '/api/drills'
      preLoaderRoute: typeof ApiDrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/$drillId': {
      id: '/drill/$drillId'
      path: '/drill/$drillId'
      fullPath: '/drill/$drillId'
      preLoaderRoute: typeof DrillDrillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/new': {
      id: '/drill/new'
      path: '/drill/new'
      fullPath: '/drill/new'
      preLoaderRoute: typeof DrillNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drills/$drillId': {
      id: '/api/drills/$drillId'
      path: '/$drillId'
      fullPath: '/api/drills/$drillId'
      preLoaderRoute: typeof ApiDrillsDrillIdRouteImport
      parentRoute: typeof ApiDrillsRoute
    }
    '/drill/$drillId_/debrief': {
      id: '/drill/$drillId_/debrief'
      path: '/drill/$drillId/debrief'
      fullPath: '/drill/$drillId/debrief'
      preLoaderRoute: typeof DrillDrillIdDebriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drills/$drillId/debrief': {
      id: '/api/drills/$drillId/debrief'
      path: '/debrief'
      fullPath: '/api/drills/$drillId/debrief'
      preLoaderRoute: typeof ApiDrillsDrillIdDebriefRouteImport
      parentRoute: typeof ApiDrillsDrillIdRoute
    }
    '/api/drills/$drillId/end': {
      id: '/api/drills/$drillId/end'
      path: '/end'
      fullPath: '/api/drills/$drillId/end'
      preLoaderRoute: typeof ApiDrillsDrillIdEndRouteImport
      parentRoute: typeof ApiDrillsDrillIdRoute
    }
    '/api/drills/$drillId/packet': {
      id: '/api/drills/$drillId/packet'
      path: '/packet'
      fullPath: '/api/drills/$drillId/packet'
      preLoaderRoute: typeof ApiDrillsDrillIdPacketRouteImport
      parentRoute: typeof ApiDrillsDrillIdRoute
    }
  }
}

interface ApiDrillsDrillIdRouteChildren {
  ApiDrillsDrillIdDebriefRoute: typeof ApiDrillsDrillIdDebriefRoute
  ApiDrillsDrillIdEndRoute: typeof ApiDrillsDrillIdEndRoute
  ApiDrillsDrillIdPacketRoute: typeof ApiDrillsDrillIdPacketRoute
}

const ApiDrillsDrillIdRouteChildren: ApiDrillsDrillIdRouteChildren = {
  ApiDrillsDrillIdDebriefRoute: ApiDrillsDrillIdDebriefRoute,
  ApiDrillsDrillIdEndRoute: ApiDrillsDrillIdEndRoute,
  ApiDrillsDrillIdPacketRoute: ApiDrillsDrillIdPacketRoute,
}

const ApiDrillsDrillIdRouteWithChildren =
  ApiDrillsDrillIdRoute._addFileChildren(ApiDrillsDrillIdRouteChildren)

interface ApiDrillsRouteChildren {
  ApiDrillsDrillIdRoute: typeof ApiDrillsDrillIdRouteWithChildren
}

const ApiDrillsRouteChildren: ApiDrillsRouteChildren = {
  ApiDrillsDrillIdRoute: ApiDrillsDrillIdRouteWithChildren,
}

const ApiDrillsRouteWithChildren = ApiDrillsRoute._addFileChildren(
  ApiDrillsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiDrillsRoute: ApiDrillsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  DrillDrillIdRoute: DrillDrillIdRoute,
  DrillNewRoute: DrillNewRoute,
  DrillDrillIdDebriefRoute: DrillDrillIdDebriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
